version: '3.8'

services:
  django:
    container_name: django
    build:
      context: ./dcelery
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dcelery:/usr/src/app/
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=123qwe
      - ALLOWED_HOSTS=localhost,127.0.0.1
